//! `/docs/typography`.

use dioxus::prelude::*;

use super::{GuidePage, GuideSection};
use crate::components::code_block::CodeBlock;
use crate::components::prose::Prose;

/// The scale this site declares, with the class that renders each step. Kept
/// next to the specimens that demonstrate them so a step cannot be documented
/// without showing what it looks like.
const SCALE: &[(&str, &str, &str)] = &[
    (
        "text-display",
        "Display",
        "Hero headings. Fluid: clamp(2.5rem → 4.5rem).",
    ),
    (
        "text-h1",
        "Heading 1",
        "Page titles. Fluid: clamp(1.875rem → 2.75rem).",
    ),
    ("text-h2", "Heading 2", "Section headings. Fixed at 1.5rem."),
    (
        "text-lead",
        "Lead",
        "Introductory paragraphs. 1.125rem, relaxed.",
    ),
];

#[component]
pub fn TypographyGuide() -> Element {
    rsx! {
        GuidePage {
            title: "Typography".to_string(),
            lead: "Type is expressed as named roles rather than ad-hoc utility stacks, so a heading is `text-h1` and not `text-3xl font-bold tracking-tight` repeated across a dozen files.".to_string(),

            GuideSection { title: "The scale".to_string(),
                div { class: "flex flex-col gap-8",
                    for (class , label , note) in SCALE {
                        div { key: "{class}", class: "flex flex-col gap-2 border-b border-border/60 pb-6 last:border-0",
                            div { class: "flex flex-wrap items-baseline gap-3",
                                code { class: "rounded border border-border/60 bg-muted px-1.5 py-0.5 font-mono text-xs", "{class}" }
                                span { class: "text-sm text-muted-foreground", "{note}" }
                            }
                            p { class: "{class}", "{label} — the quick brown fox" }
                        }
                    }
                }
                Prose { text: "The two largest steps use `clamp()` rather than breakpoints, so they scale continuously with the viewport instead of jumping at fixed widths.".to_string() }
            }

            GuideSection { title: "Font tokens".to_string(),
                Prose { text: "Families are tokens, so `font-sans` and `font-mono` resolve through them everywhere. Each carries a real fallback stack, which is what keeps text legible during `font-display: swap`.".to_string() }
                CodeBlock {
                    code: r#"@theme {
  --font-sans:    "Geist Variable", ui-sans-serif, system-ui, sans-serif;
  --font-mono:    "Geist Mono Variable", ui-monospace, monospace;
  --font-display: "Geist Variable", ui-sans-serif, system-ui, sans-serif;
}"#.to_string(),
                }
                div { class: "flex flex-col gap-3",
                    p { class: "font-sans", "font-sans — the quick brown fox jumps over the lazy dog" }
                    p { class: "font-mono", "font-mono — the quick brown fox jumps over the lazy dog" }
                }
            }

            GuideSection { title: "Swapping the typeface".to_string(),
                Prose { text: "Change the token values. Nothing else references a family name directly, so one edit moves the whole site.".to_string() }
                Prose { text: "Declare `@font-face` and the `@theme` block **above** the `adico:theme:start` marker — the region below it is regenerated by `adico add` and your declarations would be deleted. Self-hosted files belong in a *folder* asset so their names survive `dx`'s fingerprinting.".to_string() }
                CodeBlock {
                    code: r#"@font-face {
  font-family: "Your Face";
  font-weight: 100 900;          /* a variable font's full axis */
  font-display: swap;            /* show fallback text immediately */
  src: url("./fonts/your-face.woff2") format("woff2-variations");
}

@theme { --font-sans: "Your Face", ui-sans-serif, system-ui, sans-serif; }"#.to_string(),
                }
            }
        }
    }
}
