//! One page per currently migrated registry item, one file per page under
//! this directory. `index.rs` is the root route (`/`), named after
//! TanStack Start's file-based-routing convention for a directory's index
//! route (`routes.rs`'s `Route` enum still declares every path explicitly
//! -- dioxus-router has no file-system route generation).

mod accordion;
mod alert;
mod alert_dialog;
mod aspect_ratio;
mod avatar;
mod badge;
mod button;
mod calendar;
mod card;
mod checkbox;
mod collapsible;
mod color_picker;
mod combobox;
mod context_menu;
mod date_picker;
mod dialog;
mod drag_and_drop_list;
mod dropdown_menu;
mod empty;
mod hover_card;
mod index;
mod input;
mod item;
mod kbd;
mod label;
mod menubar;
mod mode_toggle;
mod pagination;
mod popover;
mod progress;
mod radio_group;
mod scroll_area;
mod select;
mod sheet;
mod sidebar;
mod skeleton;
mod slider;
mod spinner;
mod switch;
mod tabs;
mod tag_group;
mod textarea;
mod theme_switcher;
mod toast;
mod toggle;
mod toggle_group;
mod toolbar;
mod tooltip;
mod virtual_list;

pub use accordion::AccordionPage;
pub use alert::AlertPage;
pub use alert_dialog::AlertDialogPage;
pub use aspect_ratio::AspectRatioPage;
pub use avatar::AvatarPage;
pub use badge::BadgePage;
pub use button::ButtonPage;
pub use calendar::CalendarPage;
pub use card::CardPage;
pub use checkbox::CheckboxPage;
pub use collapsible::CollapsiblePage;
pub use color_picker::ColorPickerPage;
pub use combobox::ComboboxPage;
pub use context_menu::ContextMenuPage;
pub use date_picker::DatePickerPage;
pub use dialog::DialogPage;
pub use drag_and_drop_list::DragAndDropListPage;
pub use dropdown_menu::DropdownMenuPage;
pub use empty::EmptyPage;
pub use hover_card::HoverCardPage;
pub use index::Home;
pub use input::InputPage;
pub use item::ItemPage;
pub use kbd::KbdPage;
pub use label::LabelPage;
pub use menubar::MenubarPage;
pub use mode_toggle::ModeTogglePage;
pub use pagination::PaginationPage;
pub use popover::PopoverPage;
pub use progress::ProgressPage;
pub use radio_group::RadioGroupPage;
pub use scroll_area::ScrollAreaPage;
pub use select::SelectPage;
pub use sheet::SheetPage;
pub use sidebar::SidebarPage;
pub use skeleton::SkeletonPage;
pub use slider::SliderPage;
pub use spinner::SpinnerPage;
pub use switch::SwitchPage;
pub use tabs::TabsPage;
pub use tag_group::TagGroupPage;
pub use textarea::TextareaPage;
pub use theme_switcher::ThemeSwitcherPage;
pub use toast::ToastPage;
pub use toggle::TogglePage;
pub use toggle_group::ToggleGroupPage;
pub use toolbar::ToolbarPage;
pub use tooltip::TooltipPage;
pub use virtual_list::VirtualListPage;
