//! One page per currently migrated registry item, one file per page under
//! this directory. `index.rs` is the root route (`/`), named after
//! TanStack Start's file-based-routing convention for a directory's index
//! route (`routes.rs`'s `Route` enum still declares every path explicitly
//! -- dioxus-router has no file-system route generation).

mod accordion;
mod alert;
mod alert_dialog;
mod aspect_ratio;
mod attachment;
mod avatar;
mod badge;
mod breadcrumb;
mod bubble;
mod button;
mod button_group;
mod calendar;
mod card;
mod carousel;
mod checkbox;
mod collapsible;
mod color_picker;
mod combobox;
mod command;
mod context_menu;
mod data_table;
mod date_picker;
mod date_time_picker;
mod dialog;
mod drag_and_drop_list;
mod drawer;
mod dropdown_menu;
mod empty;
mod hover_card;
mod index;
mod input;
mod input_group;
mod input_otp;
mod item;
mod kbd;
mod label;
mod marker;
mod menubar;
mod message;
mod message_scroller;
mod mode_toggle;
mod native_select;
mod navigation_menu;
mod pagination;
mod popover;
mod progress;
mod radio_group;
mod resizable;
mod responsive_flow;
mod responsive_overlay;
mod scroll_area;
mod select;
mod sheet;
mod sidebar;
mod skeleton;
mod slider;
mod spinner;
mod switch;
mod table;
mod tabs;
mod tag_group;
mod textarea;
mod theme_builder;
mod theme_switcher;
mod time_picker;
mod toast;
mod toggle;
mod toggle_group;
mod toolbar;
mod tooltip;
mod virtual_list;

pub use accordion::AccordionPage;
pub use alert::AlertPage;
pub use alert_dialog::AlertDialogPage;
pub use aspect_ratio::AspectRatioPage;
pub use attachment::AttachmentPage;
pub use avatar::AvatarPage;
pub use badge::BadgePage;
pub use breadcrumb::BreadcrumbPage;
pub use bubble::BubblePage;
pub use button::ButtonPage;
pub use button_group::ButtonGroupPage;
pub use calendar::CalendarPage;
pub use card::CardPage;
pub use carousel::CarouselPage;
pub use checkbox::CheckboxPage;
pub use collapsible::CollapsiblePage;
pub use color_picker::ColorPickerPage;
pub use combobox::ComboboxPage;
pub use command::CommandPage;
pub use context_menu::ContextMenuPage;
pub use data_table::DataTablePage;
pub use date_picker::DatePickerPage;
pub use date_time_picker::DateTimePickerPage;
pub use dialog::DialogPage;
pub use drag_and_drop_list::DragAndDropListPage;
pub use drawer::DrawerPage;
pub use dropdown_menu::DropdownMenuPage;
pub use empty::EmptyPage;
pub use hover_card::HoverCardPage;
pub use index::Home;
pub use input::InputPage;
pub use input_group::InputGroupPage;
pub use input_otp::InputOTPPage;
pub use item::ItemPage;
pub use kbd::KbdPage;
pub use label::LabelPage;
pub use marker::MarkerPage;
pub use menubar::MenubarPage;
pub use message::MessagePage;
pub use message_scroller::MessageScrollerPage;
pub use mode_toggle::ModeTogglePage;
pub use native_select::NativeSelectPage;
pub use navigation_menu::NavigationMenuPage;
pub use pagination::PaginationPage;
pub use popover::PopoverPage;
pub use progress::ProgressPage;
pub use radio_group::RadioGroupPage;
pub use resizable::ResizablePage;
pub use responsive_flow::ResponsiveFlowPage;
pub use responsive_overlay::ResponsiveOverlayPage;
pub use scroll_area::ScrollAreaPage;
pub use select::SelectPage;
pub use sheet::SheetPage;
pub use sidebar::SidebarPage;
pub use skeleton::SkeletonPage;
pub use slider::SliderPage;
pub use spinner::SpinnerPage;
pub use switch::SwitchPage;
pub use table::TablePage;
pub use tabs::TabsPage;
pub use tag_group::TagGroupPage;
pub use textarea::TextareaPage;
pub use theme_builder::ThemeBuilderPage;
pub use theme_switcher::ThemeSwitcherPage;
pub use time_picker::TimePickerPage;
pub use toast::ToastPage;
pub use toggle::TogglePage;
pub use toggle_group::ToggleGroupPage;
pub use toolbar::ToolbarPage;
pub use tooltip::TooltipPage;
pub use virtual_list::VirtualListPage;
